{{- if .Values.envFrom.create }}
apiVersion: v1
data:
  CONTAINER_CONFIG: {{ .Values.envFrom.container_config_value | quote | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.envFrom.secretRefName }}
type: Opaque
{{- end }}

