{{- if .Values.envFrom.create }}

apiVersion: v1
data:
  CONTAINER_CONFIG: {{ .Values.envFrom.container_config_value | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.envFrom.secretRefName }}
type: type: Opaque
{{- end }}

